import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import Anthropic from '@anthropic-ai/sdk'
import { differenceInWeeks } from 'date-fns'
import { DEMO_STUDENTS } from '@/lib/demo/data'

const IS_DEMO = process.env.NEXT_PUBLIC_DEMO_MODE === 'true'

function buildDemoStudyPlan(studentId: string, examDate: string, focusAreas: string): string {
  const student = DEMO_STUDENTS.find((s) => s.id === studentId)
  const name = student?.full_name ?? 'the student'
  const weeks = differenceInWeeks(new Date(examDate), new Date())
  const isJEE = student?.course_id === 'course-001'
  const isNEET = student?.course_id === 'course-002'

  const subjects = isJEE
    ? 'Physics, Chemistry, Mathematics'
    : isNEET
    ? 'Physics, Chemistry, Biology'
    : 'Mathematics, Science, English'

  const focusNote = focusAreas ? `\nTeacher Focus Notes: ${focusAreas}\n` : ''

  return `📅 PERSONALIZED STUDY PLAN — ${name.toUpperCase()}
Exam Date: ${examDate} (${weeks} weeks remaining)
Subjects: ${subjects}${focusNote}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WEEK 1 — Foundation Reinforcement
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Monday
  • Physics: Mechanics — Newton's Laws, circular motion (1.5 hrs)
  • ${isJEE ? 'Mathematics' : isNEET ? 'Biology' : 'Science'}: Chapter revision + 20 NCERT questions (1 hr)
  • Evening: Review coaching notes from today's class (30 min)

Tuesday
  • Chemistry: ${isNEET ? 'Organic — Alkanes, Alkenes mechanisms' : 'Organic — Reaction mechanisms, IUPAC naming'} (1.5 hrs)
  • ${isJEE ? 'Mathematics: Quadratic equations + inequalities (1 hr)' : isNEET ? 'Biology: Cell structure & organelles (1 hr)' : 'Mathematics: Algebra practice (1 hr)'}
  • Flashcard review: Key formulas (20 min)

Wednesday
  • Physics: ${isNEET ? 'Electrostatics + Capacitance' : 'Work, Energy, Power + problems'} (1.5 hrs)
  • Chemistry: Inorganic — periodic trends, atomic structure (1 hr)
  • Doubt resolution: List unresolved concepts to ask at coaching (15 min)

Thursday
  • ${isJEE ? 'Mathematics: Trigonometry — identities and equations (1.5 hrs)' : isNEET ? 'Biology: Genetics — Mendel, heredity (1.5 hrs)' : 'English: Grammar + comprehension practice (1.5 hrs)'}
  • Chemistry: Previous year MCQs — 30 questions (1 hr)
  • Short break + light reading (30 min)

Friday
  • Full subject revision sprint: 30 min per subject (1.5 hrs)
  • ${isJEE ? 'Mathematics' : 'Physics'}: Practice set — 15 problems, timed (45 min)
  • Weekly target check: Did you complete all planned topics?

Saturday
  • Mock test: Full section test (${isJEE || isNEET ? '3 hours' : '2 hours'})
  • Analysis: Mark every wrong answer, identify pattern (1 hr)
  • Revise incorrect questions in detail (30 min)

Sunday
  • Light revision only — no new topics
  • Organize notes for Week 2
  • Rest and recharge

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WEEK 2 — Targeted Practice
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Mon–Wed: Deep dive into weakest subject from Week 1 mock
  • 2 hours/day on weak topics
  • 1 hour/day on strongest subject to maintain confidence

Thu–Fri: Cross-subject integration
  • Mixed problem sets — don't silo by subject
  • Time-bound practice (simulate exam conditions)

Saturday: Full mock test (attempt under strict time limits)
Sunday: Detailed error analysis + plan adjustment

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${weeks > 4 ? `WEEKS 3–${Math.min(weeks - 2, 8)} — Concept Mastery` : 'REMAINING WEEKS — Consolidation'}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Rotate through all subjects on a 3-day cycle
• Increase mock test frequency to 2 per week
• Target: Complete entire syllabus once + revise weak areas twice
• Track score trends — aim for +5% improvement per week

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL 2 WEEKS — Exam Readiness
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• No new topics — revision only
• 1 full mock per day (last 5 days before exam)
• Review formula sheets each morning (15 min)
• Sleep 8 hours — cognitive performance is non-negotiable
• Light exercise daily to manage stress

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DAILY TARGETS (Milestones)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Week 1 end: Mock score ≥ 50%
• Week 2 end: Mock score ≥ 60%
• Week 4 end: Mock score ≥ 70%
• Exam week: Target ≥ 75%

Generated by Claude AI for Sharma Classes — Bikaner`
}

export async function POST(request: Request) {
  const { studentId, examDate, focusAreas } = await request.json()

  // Demo mode — return pre-built realistic study plan
  if (IS_DEMO) {
    await new Promise((r) => setTimeout(r, 2200)) // realistic generation delay
    const plan = buildDemoStudyPlan(studentId, examDate, focusAreas ?? '')
    return NextResponse.json({ plan })
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: institute } = await supabase
    .from('institutes')
    .select('id, plan_tier, name')
    .eq('owner_id', user.id)
    .single()

  if (!institute || institute.plan_tier !== 'pro') {
    return NextResponse.json({ error: 'Pro plan required for AI features' }, { status: 403 })
  }

  const [studentRes, testRes] = await Promise.all([
    supabase
      .from('students')
      .select('full_name, batches(name), courses(name, subjects)')
      .eq('id', studentId)
      .single(),
    supabase
      .from('test_scores')
      .select('marks_obtained, max_marks, tests(name, test_type, test_date)')
      .eq('student_id', studentId)
      .order('tests(test_date)', { ascending: false })
      .limit(5),
  ])

  const student = studentRes.data
  if (!student) return NextResponse.json({ error: 'Student not found' }, { status: 404 })

  const course = (student.courses as unknown as { name: string; subjects: string[] }[] | null)?.[0] ?? null
  const batch = (student.batches as unknown as { name: string }[] | null)?.[0] ?? null
  const weeksUntilExam = differenceInWeeks(new Date(examDate), new Date())
  const tests = testRes.data ?? []

  const testSummary = tests.map((t) => {
    const test = (t.tests as unknown as { name: string; test_type: string }[] | null)?.[0] ?? null
    const pct = t.max_marks > 0 ? Math.round((t.marks_obtained / t.max_marks) * 100) : 0
    return `${test?.name ?? 'Test'}: ${pct}%`
  }).join(', ')

  const subjects = course?.subjects?.join(', ') ?? 'all subjects'

  const prompt = `Create a detailed week-by-week study plan for ${student.full_name} preparing for an exam on ${examDate} (${weeksUntilExam} weeks away).

Student Info:
- Course: ${course?.name ?? 'General'}
- Batch: ${batch?.name ?? 'N/A'}
- Subjects: ${subjects}
- Recent Test Scores: ${testSummary || 'No recent tests'}
${focusAreas ? `- Teacher Notes: ${focusAreas}` : ''}

Create a structured week-by-week study schedule that:
1. Prioritizes weak subjects based on recent scores
2. Allocates daily study hours realistically (2-4 hours for coaching students)
3. Includes revision weeks before the exam
4. Recommends specific practice activities per subject
5. Includes short-term milestones to track progress

Format as a clear week-by-week plan with daily breakdowns for the first 2 weeks, then weekly summaries. Be specific to the subjects provided.`

  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 1200,
    messages: [{ role: 'user', content: prompt }],
  })

  const plan = (response.content[0] as { type: string; text: string }).text

  await supabase.from('ai_usage').insert({
    institute_id: institute.id,
    feature: 'study_plan',
    student_id: studentId,
    input_tokens: response.usage.input_tokens,
    output_tokens: response.usage.output_tokens,
    cost_usd: (response.usage.input_tokens * 0.000003) + (response.usage.output_tokens * 0.000015),
  })

  return NextResponse.json({ plan })
}
